
name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.*'
      - run: dotnet publish -c Release --runtime win-x64
      - run: powershell Compress-7Zip $env:GITHUB_WORKSPACE\DotNetDllPathPatcherWPF\bin\Release\net6.0-windows\publish\win-x64 -ArchiveFileName "DotNetDllPathPatcherWPF.zip" -Format Zip
      - run: powershell Compress-7Zip $env:GITHUB_WORKSPACE\DotNetDllPathPatcherCMD\bin\Release\net6.0\publish\win-x64 -ArchiveFileName "DotNetDllPathPatcherCMD.zip" -Format Zip
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "DotNetDllPathPatcherWPF.zip,DotNetDllPathPatcherCMD.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Create a Release CMD
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "DotNetDllPathPatcherCMD.zip"
#           token: ${{ secrets.GITHUB_TOKEN }}
        
