
name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.101'
      #- run: dotnet build DotNetDllPathPatcherWPF
      - run: dotnet publish -c Release --runtime win-x64
      #- run: zip -q -r bin\Release\netcoreapp3.1\DotNetDllPathPatcherWPF.zip 
      - run: Compress-7Zip "bin\Release\netcoreapp3.1\publish" -ArchiveFileName "DotNetDllPathPatcherWPF.zip" -Format Zip
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "DotNetDllPathPatcherWPF.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
        
